'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Cufex_Security_ProfilesDetails
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''SearchRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchRow As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''SearchRow2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchRow2 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''SearchRow3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchRow3 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''QueryUrlStr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QueryUrlStr As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
