'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Cufex_Site
    
    '''<summary>
    '''metaPlaceHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents metaPlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''Cufex_CommonCss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cufex_CommonCss As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''Cufex_HeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cufex_HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''MasterPageBodyTag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MasterPageBodyTag As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''DivMainContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMainContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''TableNotloggedIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableNotloggedIn As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Home_Def control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Home_Def As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Home_Def_MenuArrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Home_Def_MenuArrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Security control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Security As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Security_MenuArrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Security_MenuArrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Security_ChangePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Security_ChangePassword As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Security_Users control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Security_Users As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Security_UsersControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Security_UsersControl As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Security_Profiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Security_Profiles As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Security_UserProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Security_UserProfile As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Configuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Configuration As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Configuration_MenuArrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Configuration_MenuArrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Configuration_ShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Configuration_ShipTo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Configuration_ShipFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Configuration_ShipFrom As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Configuration_Items control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Configuration_Items As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Configuration_ItemCatalogue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Configuration_ItemCatalogue As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Warehouse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Warehouse As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Warehouse_MenuArrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Warehouse_MenuArrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Warehouse_PO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Warehouse_PO As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Warehouse_ASN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Warehouse_ASN As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Warehouse_Shipment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Warehouse_Shipment As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Warehouse_OrderManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Warehouse_OrderManagement As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Inventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Inventory As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Inventory_MenuArrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Inventory_MenuArrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Inventory_Balance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Inventory_Balance As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Reporting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Reporting As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Reporting_MenuArrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Reporting_MenuArrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Reporting_ViewReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Reporting_ViewReports As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Cufex_MasterHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cufex_MasterHeader As Global.SNSsoftware.Cufex_MasterHeader
    
    '''<summary>
    '''Cufex_MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cufex_MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''DivDenied control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivDenied As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LogInContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogInContainer As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''fromdefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fromdefault As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertTitle As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertText As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertType As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertallowOutsideClick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertallowOutsideClick As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertshowCancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertshowCancelButton As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertconfirmButtonText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertconfirmButtonText As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertconfirmButtonColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertconfirmButtonColor As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertcancelButtonText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertcancelButtonText As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertcloseOnConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertcloseOnConfirm As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertimageUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertimageUrl As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertimageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertimageSize As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''Alerttimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Alerttimer As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenMenuStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenMenuStatus As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''Cufex_ScriptContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cufex_ScriptContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
