'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Cufex_Site
    
    '''<summary>
    '''metaPlaceHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents metaPlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''Cufex_CommonCss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cufex_CommonCss As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''Cufex_HeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cufex_HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''MasterPageBodyTag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MasterPageBodyTag As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''DivMainContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMainContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''TableNotloggedIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableNotloggedIn As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''widthMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents widthMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SideMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SideMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''MainLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainLogo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Home_Def control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Home_Def As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Home_Def_MenuArrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Home_Def_MenuArrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Administration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Administration As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Administration_MenuArrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Administration_MenuArrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Administration_ExportLogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Administration_ExportLogs As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Administration_ImportLogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Administration_ImportLogs As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Administration_FileManagementLogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Administration_FileManagementLogs As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Administration_FileManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Administration_FileManagement As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Administration_UITemplates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Administration_UITemplates As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Security control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Security As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Security_MenuArrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Security_MenuArrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Security_ChangePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Security_ChangePassword As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Security_Users control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Security_Users As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Security_UsersControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Security_UsersControl As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Security_Profiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Security_Profiles As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Security_UserProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Security_UserProfile As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Configuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Configuration As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Configuration_MenuArrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Configuration_MenuArrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Configuration_ShipTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Configuration_ShipTo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Configuration_ShipFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Configuration_ShipFrom As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Configuration_Items control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Configuration_Items As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Configuration_ItemCatalogue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Configuration_ItemCatalogue As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Warehouse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Warehouse As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Warehouse_MenuArrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Warehouse_MenuArrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Warehouse_PO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Warehouse_PO As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Warehouse_ASN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Warehouse_ASN As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Warehouse_Shipment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Warehouse_Shipment As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Warehouse_OrderManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Warehouse_OrderManagement As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Warehouse_OrderTracking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Warehouse_OrderTracking As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Inventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Inventory As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Inventory_MenuArrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Inventory_MenuArrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Inventory_Balance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Inventory_Balance As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Reporting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Reporting As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain_Reporting_MenuArrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain_Reporting_MenuArrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivSubMain_Reporting_ViewReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSubMain_Reporting_ViewReports As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''widthContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents widthContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DivMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivMain As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''CarrierEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CarrierEvents As Global.SNSsoftware.Cufex_Warehouse_OrderTracking_CarrierEvents
    
    '''<summary>
    '''HeaderMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeaderMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Cufex_MasterHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cufex_MasterHeader As Global.SNSsoftware.Cufex_MasterHeader
    
    '''<summary>
    '''Cufex_MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cufex_MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''DivDenied control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivDenied As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LogInContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogInContainer As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''fromdefault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fromdefault As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertTitle As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertText As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertType As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertallowOutsideClick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertallowOutsideClick As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertshowCancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertshowCancelButton As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertconfirmButtonText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertconfirmButtonText As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertconfirmButtonColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertconfirmButtonColor As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertcancelButtonText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertcancelButtonText As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertcloseOnConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertcloseOnConfirm As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertimageUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertimageUrl As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''AlertimageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertimageSize As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''Alerttimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Alerttimer As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenMenuStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenMenuStatus As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''Cufex_ScriptContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cufex_ScriptContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''HiddenMenuOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenMenuOpen As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenFileImportLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFileImportLimit As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenFileUploadLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFileUploadLimit As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenLoginBackgroundColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenLoginBackgroundColor As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenMenuBackgroundColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenMenuBackgroundColor As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenScreenBackgroundColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenScreenBackgroundColor As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenGridBackgroundColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenGridBackgroundColor As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenButtonBackgroundColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenButtonBackgroundColor As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''HiddenTextBackgroundColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenTextBackgroundColor As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
