'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.Resources", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ABC Analysis Report.
        '''</summary>
        Friend Shared ReadOnly Property ABCAnalysisReport() As String
            Get
                Return ResourceManager.GetString("ABCAnalysisReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actions.
        '''</summary>
        Friend Shared ReadOnly Property Actions() As String
            Get
                Return ResourceManager.GetString("Actions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Active.
        '''</summary>
        Friend Shared ReadOnly Property Active() As String
            Get
                Return ResourceManager.GetString("Active", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actual ShipDate.
        '''</summary>
        Friend Shared ReadOnly Property ActualShipDate() As String
            Get
                Return ResourceManager.GetString("ActualShipDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend Shared ReadOnly Property Add() As String
            Get
                Return ResourceManager.GetString("Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address1.
        '''</summary>
        Friend Shared ReadOnly Property Address1() As String
            Get
                Return ResourceManager.GetString("Address1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address2.
        '''</summary>
        Friend Shared ReadOnly Property Address2() As String
            Get
                Return ResourceManager.GetString("Address2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address3.
        '''</summary>
        Friend Shared ReadOnly Property Address3() As String
            Get
                Return ResourceManager.GetString("Address3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address4.
        '''</summary>
        Friend Shared ReadOnly Property Address4() As String
            Get
                Return ResourceManager.GetString("Address4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address5.
        '''</summary>
        Friend Shared ReadOnly Property Address5() As String
            Get
                Return ResourceManager.GetString("Address5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address6.
        '''</summary>
        Friend Shared ReadOnly Property Address6() As String
            Get
                Return ResourceManager.GetString("Address6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adjustment/Reason code KPI.
        '''</summary>
        Friend Shared ReadOnly Property AdjustmentReasoncodeKPI() As String
            Get
                Return ResourceManager.GetString("AdjustmentReasoncodeKPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adjustment Reasons.
        '''</summary>
        Friend Shared ReadOnly Property AdjustmentReasons() As String
            Get
                Return ResourceManager.GetString("AdjustmentReasons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allocate.
        '''</summary>
        Friend Shared ReadOnly Property Allocate() As String
            Get
                Return ResourceManager.GetString("Allocate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allocated Qty.
        '''</summary>
        Friend Shared ReadOnly Property AllocatedQty() As String
            Get
                Return ResourceManager.GetString("AllocatedQty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All Owners.
        '''</summary>
        Friend Shared ReadOnly Property AllOwners() As String
            Get
                Return ResourceManager.GetString("AllOwners", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ASN.
        '''</summary>
        Friend Shared ReadOnly Property ASN() As String
            Get
                Return ResourceManager.GetString("ASN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ASN/Receipt.
        '''</summary>
        Friend Shared ReadOnly Property ASNReceipt() As String
            Get
                Return ResourceManager.GetString("ASNReceipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available Qty.
        '''</summary>
        Friend Shared ReadOnly Property AvailableQty() As String
            Get
                Return ResourceManager.GetString("AvailableQty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buyer.
        '''</summary>
        Friend Shared ReadOnly Property Buyer() As String
            Get
                Return ResourceManager.GetString("Buyer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buyer Reference.
        '''</summary>
        Friend Shared ReadOnly Property BuyerReference() As String
            Get
                Return ResourceManager.GetString("BuyerReference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carrier.
        '''</summary>
        Friend Shared ReadOnly Property Carrier() As String
            Get
                Return ResourceManager.GetString("Carrier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Category.
        '''</summary>
        Friend Shared ReadOnly Property Category() As String
            Get
                Return ResourceManager.GetString("Category", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Password.
        '''</summary>
        Friend Shared ReadOnly Property ChangePassword() As String
            Get
                Return ResourceManager.GetString("ChangePassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to City.
        '''</summary>
        Friend Shared ReadOnly Property City() As String
            Get
                Return ResourceManager.GetString("City", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close To Expiry Report.
        '''</summary>
        Friend Shared ReadOnly Property CloseToExpiryReport() As String
            Get
                Return ResourceManager.GetString("CloseToExpiryReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commingle Items.
        '''</summary>
        Friend Shared ReadOnly Property CommingleItems() As String
            Get
                Return ResourceManager.GetString("CommingleItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commingle Lots.
        '''</summary>
        Friend Shared ReadOnly Property CommingleLots() As String
            Get
                Return ResourceManager.GetString("CommingleLots", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company.
        '''</summary>
        Friend Shared ReadOnly Property Company() As String
            Get
                Return ResourceManager.GetString("Company", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration.
        '''</summary>
        Friend Shared ReadOnly Property Configuration() As String
            Get
                Return ResourceManager.GetString("Configuration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm Password.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmPassword() As String
            Get
                Return ResourceManager.GetString("ConfirmPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consignee.
        '''</summary>
        Friend Shared ReadOnly Property Consignee() As String
            Get
                Return ResourceManager.GetString("Consignee", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consignee Key.
        '''</summary>
        Friend Shared ReadOnly Property ConsigneeKey() As String
            Get
                Return ResourceManager.GetString("ConsigneeKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consignee Name.
        '''</summary>
        Friend Shared ReadOnly Property ConsigneeName() As String
            Get
                Return ResourceManager.GetString("ConsigneeName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact1.
        '''</summary>
        Friend Shared ReadOnly Property Contact1() As String
            Get
                Return ResourceManager.GetString("Contact1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact2.
        '''</summary>
        Friend Shared ReadOnly Property Contact2() As String
            Get
                Return ResourceManager.GetString("Contact2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Container Ref.
        '''</summary>
        Friend Shared ReadOnly Property ContainerRef() As String
            Get
                Return ResourceManager.GetString("ContainerRef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Container Reference.
        '''</summary>
        Friend Shared ReadOnly Property ContainerReference() As String
            Get
                Return ResourceManager.GetString("ContainerReference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Container Type.
        '''</summary>
        Friend Shared ReadOnly Property ContainerType() As String
            Get
                Return ResourceManager.GetString("ContainerType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Country.
        '''</summary>
        Friend Shared ReadOnly Property Country() As String
            Get
                Return ResourceManager.GetString("Country", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Country of Origin.
        '''</summary>
        Friend Shared ReadOnly Property CountryofOrigin() As String
            Get
                Return ResourceManager.GetString("CountryofOrigin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cube.
        '''</summary>
        Friend Shared ReadOnly Property Cube() As String
            Get
                Return ResourceManager.GetString("Cube", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Currency.
        '''</summary>
        Friend Shared ReadOnly Property Currency() As String
            Get
                Return ResourceManager.GetString("Currency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property Delete() As String
            Get
                Return ResourceManager.GetString("Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete the selected item(s)?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteConfirmation() As String
            Get
                Return ResourceManager.GetString("DeleteConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property Description() As String
            Get
                Return ResourceManager.GetString("Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend Shared ReadOnly Property Edit() As String
            Get
                Return ResourceManager.GetString("Edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Effective Date.
        '''</summary>
        Friend Shared ReadOnly Property EffectiveDate() As String
            Get
                Return ResourceManager.GetString("EffectiveDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Friend Shared ReadOnly Property Email() As String
            Get
                Return ResourceManager.GetString("Email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email1.
        '''</summary>
        Friend Shared ReadOnly Property Email1() As String
            Get
                Return ResourceManager.GetString("Email1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email2.
        '''</summary>
        Friend Shared ReadOnly Property Email2() As String
            Get
                Return ResourceManager.GetString("Email2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dear &lt;b&gt;{0}&lt;/b&gt;,
        '''&lt;br/&gt;
        '''&lt;br/&gt;
        '''Your password reset code: &lt;b&gt;{1}&lt;/b&gt;
        '''&lt;br/&gt;
        '''&lt;br/&gt;
        '''&lt;b&gt;If you did not request to change password please ignore this message.&lt;/b&gt;
        '''&lt;br/&gt;
        '''&lt;br/&gt;
        '''SNS.
        '''</summary>
        Friend Shared ReadOnly Property Email_PasswordCode() As String
            Get
                Return ResourceManager.GetString("Email_PasswordCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dear &lt;b&gt;{0}&lt;/b&gt;,
        '''&lt;br/&gt;
        '''&lt;br/&gt;
        '''Your password has been changed by the administrator.&lt;br/&gt;
        '''New Password: &lt;b&gt;{1}&lt;/b&gt;
        '''&lt;br/&gt;
        '''&lt;br/&gt;
        '''&lt;b&gt;Please consider changing your password soon.&lt;/b&gt;
        '''&lt;br/&gt;
        '''&lt;br/&gt;
        '''SNS..
        '''</summary>
        Friend Shared ReadOnly Property Email_PasswordReset() As String
            Get
                Return ResourceManager.GetString("Email_PasswordReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entry.
        '''</summary>
        Friend Shared ReadOnly Property Entry() As String
            Get
                Return ResourceManager.GetString("Entry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Explode.
        '''</summary>
        Friend Shared ReadOnly Property Explode() As String
            Get
                Return ResourceManager.GetString("Explode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extern Line#.
        '''</summary>
        Friend Shared ReadOnly Property ExternLine() As String
            Get
                Return ResourceManager.GetString("ExternLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extern Line No.
        '''</summary>
        Friend Shared ReadOnly Property ExternLineNo() As String
            Get
                Return ResourceManager.GetString("ExternLineNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extern Order Key.
        '''</summary>
        Friend Shared ReadOnly Property ExternOrderKey() As String
            Get
                Return ResourceManager.GetString("ExternOrderKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extern PO.
        '''</summary>
        Friend Shared ReadOnly Property ExternPO() As String
            Get
                Return ResourceManager.GetString("ExternPO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extern ReceiptKey.
        '''</summary>
        Friend Shared ReadOnly Property ExternReceiptKey() As String
            Get
                Return ResourceManager.GetString("ExternReceiptKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Facility.
        '''</summary>
        Friend Shared ReadOnly Property Facility() As String
            Get
                Return ResourceManager.GetString("Facility", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Name.
        '''</summary>
        Friend Shared ReadOnly Property FirstName() As String
            Get
                Return ResourceManager.GetString("FirstName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flag.
        '''</summary>
        Friend Shared ReadOnly Property Flag() As String
            Get
                Return ResourceManager.GetString("Flag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From ASN.
        '''</summary>
        Friend Shared ReadOnly Property FromASN() As String
            Get
                Return ResourceManager.GetString("FromASN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From Customer Order.
        '''</summary>
        Friend Shared ReadOnly Property FromCustomerOrder() As String
            Get
                Return ResourceManager.GetString("FromCustomerOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From Date.
        '''</summary>
        Friend Shared ReadOnly Property FromDate() As String
            Get
                Return ResourceManager.GetString("FromDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From Order.
        '''</summary>
        Friend Shared ReadOnly Property FromOrder() As String
            Get
                Return ResourceManager.GetString("FromOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From Order Date.
        '''</summary>
        Friend Shared ReadOnly Property FromOrderDate() As String
            Get
                Return ResourceManager.GetString("FromOrderDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From Ship Date.
        '''</summary>
        Friend Shared ReadOnly Property FromShipDate() As String
            Get
                Return ResourceManager.GetString("FromShipDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From Sku.
        '''</summary>
        Friend Shared ReadOnly Property FromSku() As String
            Get
                Return ResourceManager.GetString("FromSku", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From Storer.
        '''</summary>
        Friend Shared ReadOnly Property FromStorer() As String
            Get
                Return ResourceManager.GetString("FromStorer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From Zone.
        '''</summary>
        Friend Shared ReadOnly Property FromZone() As String
            Get
                Return ResourceManager.GetString("FromZone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gross Wgt.
        '''</summary>
        Friend Shared ReadOnly Property GrossWgt() As String
            Get
                Return ResourceManager.GetString("GrossWgt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to History.
        '''</summary>
        Friend Shared ReadOnly Property History() As String
            Get
                Return ResourceManager.GetString("History", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hold.
        '''</summary>
        Friend Shared ReadOnly Property Hold() As String
            Get
                Return ResourceManager.GetString("Hold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Home.
        '''</summary>
        Friend Shared ReadOnly Property Home() As String
            Get
                Return ResourceManager.GetString("Home", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend Shared ReadOnly Property ID() As String
            Get
                Return ResourceManager.GetString("ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory.
        '''</summary>
        Friend Shared ReadOnly Property Inventory() As String
            Get
                Return ResourceManager.GetString("Inventory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory Adjustment Summary Report.
        '''</summary>
        Friend Shared ReadOnly Property InventoryAdjustmentSummaryReport() As String
            Get
                Return ResourceManager.GetString("InventoryAdjustmentSummaryReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory Balance.
        '''</summary>
        Friend Shared ReadOnly Property InventoryBalance() As String
            Get
                Return ResourceManager.GetString("InventoryBalance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory Hold KPI.
        '''</summary>
        Friend Shared ReadOnly Property InventoryHoldKPI() As String
            Get
                Return ResourceManager.GetString("InventoryHoldKPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item.
        '''</summary>
        Friend Shared ReadOnly Property Item() As String
            Get
                Return ResourceManager.GetString("Item", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Catalogue.
        '''</summary>
        Friend Shared ReadOnly Property ItemCatalogue() As String
            Get
                Return ResourceManager.GetString("ItemCatalogue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Catalogue Details.
        '''</summary>
        Friend Shared ReadOnly Property ItemCatalogueDetails() As String
            Get
                Return ResourceManager.GetString("ItemCatalogueDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Description.
        '''</summary>
        Friend Shared ReadOnly Property ItemDescription() As String
            Get
                Return ResourceManager.GetString("ItemDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Details.
        '''</summary>
        Friend Shared ReadOnly Property ItemDetails() As String
            Get
                Return ResourceManager.GetString("ItemDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Group.
        '''</summary>
        Friend Shared ReadOnly Property ItemGroup() As String
            Get
                Return ResourceManager.GetString("ItemGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items.
        '''</summary>
        Friend Shared ReadOnly Property Items() As String
            Get
                Return ResourceManager.GetString("Items", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Key.
        '''</summary>
        Friend Shared ReadOnly Property Key() As String
            Get
                Return ResourceManager.GetString("Key", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to KPIs.
        '''</summary>
        Friend Shared ReadOnly Property KPIs() As String
            Get
                Return ResourceManager.GetString("KPIs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to KPI Title.
        '''</summary>
        Friend Shared ReadOnly Property KPITitle() As String
            Get
                Return ResourceManager.GetString("KPITitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Name.
        '''</summary>
        Friend Shared ReadOnly Property LastName() As String
            Get
                Return ResourceManager.GetString("LastName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line#.
        '''</summary>
        Friend Shared ReadOnly Property Line() As String
            Get
                Return ResourceManager.GetString("Line", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load.
        '''</summary>
        Friend Shared ReadOnly Property Load() As String
            Get
                Return ResourceManager.GetString("Load", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load Widget.
        '''</summary>
        Friend Shared ReadOnly Property LoadWidget() As String
            Get
                Return ResourceManager.GetString("LoadWidget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location.
        '''</summary>
        Friend Shared ReadOnly Property Location() As String
            Get
                Return ResourceManager.GetString("Location", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LOGIN.
        '''</summary>
        Friend Shared ReadOnly Property LOGIN() As String
            Get
                Return ResourceManager.GetString("LOGIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logout.
        '''</summary>
        Friend Shared ReadOnly Property Logout() As String
            Get
                Return ResourceManager.GetString("Logout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to logout?.
        '''</summary>
        Friend Shared ReadOnly Property LogoutConfirm() As String
            Get
                Return ResourceManager.GetString("LogoutConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LoseId.
        '''</summary>
        Friend Shared ReadOnly Property LoseId() As String
            Get
                Return ResourceManager.GetString("LoseId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lottable.
        '''</summary>
        Friend Shared ReadOnly Property Lottable() As String
            Get
                Return ResourceManager.GetString("Lottable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lottable01.
        '''</summary>
        Friend Shared ReadOnly Property Lottable01() As String
            Get
                Return ResourceManager.GetString("Lottable01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lottable02.
        '''</summary>
        Friend Shared ReadOnly Property Lottable02() As String
            Get
                Return ResourceManager.GetString("Lottable02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lottable03.
        '''</summary>
        Friend Shared ReadOnly Property Lottable03() As String
            Get
                Return ResourceManager.GetString("Lottable03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lottable04.
        '''</summary>
        Friend Shared ReadOnly Property Lottable04() As String
            Get
                Return ResourceManager.GetString("Lottable04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lottable05.
        '''</summary>
        Friend Shared ReadOnly Property Lottable05() As String
            Get
                Return ResourceManager.GetString("Lottable05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lottable06.
        '''</summary>
        Friend Shared ReadOnly Property Lottable06() As String
            Get
                Return ResourceManager.GetString("Lottable06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lottable07.
        '''</summary>
        Friend Shared ReadOnly Property Lottable07() As String
            Get
                Return ResourceManager.GetString("Lottable07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lottable08.
        '''</summary>
        Friend Shared ReadOnly Property Lottable08() As String
            Get
                Return ResourceManager.GetString("Lottable08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lottable09.
        '''</summary>
        Friend Shared ReadOnly Property Lottable09() As String
            Get
                Return ResourceManager.GetString("Lottable09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lottable10.
        '''</summary>
        Friend Shared ReadOnly Property Lottable10() As String
            Get
                Return ResourceManager.GetString("Lottable10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lottable11.
        '''</summary>
        Friend Shared ReadOnly Property Lottable11() As String
            Get
                Return ResourceManager.GetString("Lottable11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lottable12.
        '''</summary>
        Friend Shared ReadOnly Property Lottable12() As String
            Get
                Return ResourceManager.GetString("Lottable12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Management Order#.
        '''</summary>
        Friend Shared ReadOnly Property ManagementOrder() As String
            Get
                Return ResourceManager.GetString("ManagementOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max Expiry Date.
        '''</summary>
        Friend Shared ReadOnly Property MaxExpiryDate() As String
            Get
                Return ResourceManager.GetString("MaxExpiryDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Measured By.
        '''</summary>
        Friend Shared ReadOnly Property MeasuredBy() As String
            Get
                Return ResourceManager.GetString("MeasuredBy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Min Expiry Date.
        '''</summary>
        Friend Shared ReadOnly Property MinExpiryDate() As String
            Get
                Return ResourceManager.GetString("MinExpiryDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NB# of Orders Not Released to WMS KPI.
        '''</summary>
        Friend Shared ReadOnly Property NBofOrdersNotReleasedtoWMSKPI() As String
            Get
                Return ResourceManager.GetString("NBofOrdersNotReleasedtoWMSKPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NB# of Pending Orders KPI.
        '''</summary>
        Friend Shared ReadOnly Property NBofPendingOrdersKPI() As String
            Get
                Return ResourceManager.GetString("NBofPendingOrdersKPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Net Wgt.
        '''</summary>
        Friend Shared ReadOnly Property NetWgt() As String
            Get
                Return ResourceManager.GetString("NetWgt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Asn.
        '''</summary>
        Friend Shared ReadOnly Property NewAsn() As String
            Get
                Return ResourceManager.GetString("NewAsn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New ASN/Receipt.
        '''</summary>
        Friend Shared ReadOnly Property NewASNReceipt() As String
            Get
                Return ResourceManager.GetString("NewASNReceipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Detail.
        '''</summary>
        Friend Shared ReadOnly Property NewDetail() As String
            Get
                Return ResourceManager.GetString("NewDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Item.
        '''</summary>
        Friend Shared ReadOnly Property NewItem() As String
            Get
                Return ResourceManager.GetString("NewItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Item Catalogue.
        '''</summary>
        Friend Shared ReadOnly Property NewItemCatalogue() As String
            Get
                Return ResourceManager.GetString("NewItemCatalogue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Order.
        '''</summary>
        Friend Shared ReadOnly Property NewOrder() As String
            Get
                Return ResourceManager.GetString("NewOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Order Management.
        '''</summary>
        Friend Shared ReadOnly Property NewOrderManagement() As String
            Get
                Return ResourceManager.GetString("NewOrderManagement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Password.
        '''</summary>
        Friend Shared ReadOnly Property NewPassword() As String
            Get
                Return ResourceManager.GetString("NewPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New PO.
        '''</summary>
        Friend Shared ReadOnly Property NewPO() As String
            Get
                Return ResourceManager.GetString("NewPO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Profile.
        '''</summary>
        Friend Shared ReadOnly Property NewProfile() As String
            Get
                Return ResourceManager.GetString("NewProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Purchase Order.
        '''</summary>
        Friend Shared ReadOnly Property NewPurchaseOrder() As String
            Get
                Return ResourceManager.GetString("NewPurchaseOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Shipment Order.
        '''</summary>
        Friend Shared ReadOnly Property NewShipmentOrder() As String
            Get
                Return ResourceManager.GetString("NewShipmentOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Ship To.
        '''</summary>
        Friend Shared ReadOnly Property NewShipTo() As String
            Get
                Return ResourceManager.GetString("NewShipTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New SO.
        '''</summary>
        Friend Shared ReadOnly Property NewSO() As String
            Get
                Return ResourceManager.GetString("NewSO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Supplier.
        '''</summary>
        Friend Shared ReadOnly Property NewSupplier() As String
            Get
                Return ResourceManager.GetString("NewSupplier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New User.
        '''</summary>
        Friend Shared ReadOnly Property NewUser() As String
            Get
                Return ResourceManager.GetString("NewUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New User Control.
        '''</summary>
        Friend Shared ReadOnly Property NewUserControl() As String
            Get
                Return ResourceManager.GetString("NewUserControl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend Shared ReadOnly Property No() As String
            Get
                Return ResourceManager.GetString("No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Qty.
        '''</summary>
        Friend Shared ReadOnly Property OpenQty() As String
            Get
                Return ResourceManager.GetString("OpenQty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Order.
        '''</summary>
        Friend Shared ReadOnly Property Order() As String
            Get
                Return ResourceManager.GetString("Order", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Order Date.
        '''</summary>
        Friend Shared ReadOnly Property OrderDate() As String
            Get
                Return ResourceManager.GetString("OrderDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Order Key.
        '''</summary>
        Friend Shared ReadOnly Property OrderKey() As String
            Get
                Return ResourceManager.GetString("OrderKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Order Management.
        '''</summary>
        Friend Shared ReadOnly Property OrderManagement() As String
            Get
                Return ResourceManager.GetString("OrderManagement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Order Management Entry.
        '''</summary>
        Friend Shared ReadOnly Property OrderManagementEntry() As String
            Get
                Return ResourceManager.GetString("OrderManagementEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Order ManagKey.
        '''</summary>
        Friend Shared ReadOnly Property OrderManagKey() As String
            Get
                Return ResourceManager.GetString("OrderManagKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Orders Not Released to WMS KPI.
        '''</summary>
        Friend Shared ReadOnly Property OrdersNotReleasedtoWMSKPI() As String
            Get
                Return ResourceManager.GetString("OrdersNotReleasedtoWMSKPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Original Password.
        '''</summary>
        Friend Shared ReadOnly Property OriginalPassword() As String
            Get
                Return ResourceManager.GetString("OriginalPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Original Qty.
        '''</summary>
        Friend Shared ReadOnly Property OriginalQty() As String
            Get
                Return ResourceManager.GetString("OriginalQty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Owner.
        '''</summary>
        Friend Shared ReadOnly Property Owner() As String
            Get
                Return ResourceManager.GetString("Owner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pack.
        '''</summary>
        Friend Shared ReadOnly Property Pack() As String
            Get
                Return ResourceManager.GetString("Pack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pack Description.
        '''</summary>
        Friend Shared ReadOnly Property PackDescription() As String
            Get
                Return ResourceManager.GetString("PackDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Packing List Report.
        '''</summary>
        Friend Shared ReadOnly Property PackingListReport() As String
            Get
                Return ResourceManager.GetString("PackingListReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property Password() As String
            Get
                Return ResourceManager.GetString("Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to * Password must be at least 10 characters, have one upper case letter, one lower case letter and one base 10 digits (0 to 9).
        '''</summary>
        Friend Shared ReadOnly Property PasswordQuote() As String
            Get
                Return ResourceManager.GetString("PasswordQuote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pending Orders KPI.
        '''</summary>
        Friend Shared ReadOnly Property PendingOrdersKPI() As String
            Get
                Return ResourceManager.GetString("PendingOrdersKPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You do not have permission to this screen.
        '''</summary>
        Friend Shared ReadOnly Property PermissionError() As String
            Get
                Return ResourceManager.GetString("PermissionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phone1.
        '''</summary>
        Friend Shared ReadOnly Property Phone1() As String
            Get
                Return ResourceManager.GetString("Phone1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phone2.
        '''</summary>
        Friend Shared ReadOnly Property Phone2() As String
            Get
                Return ResourceManager.GetString("Phone2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Picked Qty.
        '''</summary>
        Friend Shared ReadOnly Property PickedQty() As String
            Get
                Return ResourceManager.GetString("PickedQty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PO.
        '''</summary>
        Friend Shared ReadOnly Property PO() As String
            Get
                Return ResourceManager.GetString("PO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PO Date.
        '''</summary>
        Friend Shared ReadOnly Property PODate() As String
            Get
                Return ResourceManager.GetString("PODate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PO Key.
        '''</summary>
        Friend Shared ReadOnly Property POKey() As String
            Get
                Return ResourceManager.GetString("POKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PO Number.
        '''</summary>
        Friend Shared ReadOnly Property PONumber() As String
            Get
                Return ResourceManager.GetString("PONumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price.
        '''</summary>
        Friend Shared ReadOnly Property Price() As String
            Get
                Return ResourceManager.GetString("Price", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print Receiving Tally Sheet.
        '''</summary>
        Friend Shared ReadOnly Property PrintReceivingTallySheet() As String
            Get
                Return ResourceManager.GetString("PrintReceivingTallySheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Profile.
        '''</summary>
        Friend Shared ReadOnly Property Profile() As String
            Get
                Return ResourceManager.GetString("Profile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Profile Details.
        '''</summary>
        Friend Shared ReadOnly Property ProfileDetails() As String
            Get
                Return ResourceManager.GetString("ProfileDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Profile Name.
        '''</summary>
        Friend Shared ReadOnly Property ProfileName() As String
            Get
                Return ResourceManager.GetString("ProfileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Profiles.
        '''</summary>
        Friend Shared ReadOnly Property Profiles() As String
            Get
                Return ResourceManager.GetString("Profiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Purchase Order.
        '''</summary>
        Friend Shared ReadOnly Property PurchaseOrder() As String
            Get
                Return ResourceManager.GetString("PurchaseOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Purchase Order#.
        '''</summary>
        Friend Shared ReadOnly Property PurchaseOrder1() As String
            Get
                Return ResourceManager.GetString("PurchaseOrder1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qty Available.
        '''</summary>
        Friend Shared ReadOnly Property QtyAvailable() As String
            Get
                Return ResourceManager.GetString("QtyAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qty Expected.
        '''</summary>
        Friend Shared ReadOnly Property QtyExpected() As String
            Get
                Return ResourceManager.GetString("QtyExpected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qty on Hand.
        '''</summary>
        Friend Shared ReadOnly Property QtyonHand() As String
            Get
                Return ResourceManager.GetString("QtyonHand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qty Ordered.
        '''</summary>
        Friend Shared ReadOnly Property QtyOrdered() As String
            Get
                Return ResourceManager.GetString("QtyOrdered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qty Picked.
        '''</summary>
        Friend Shared ReadOnly Property QtyPicked() As String
            Get
                Return ResourceManager.GetString("QtyPicked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qty Received.
        '''</summary>
        Friend Shared ReadOnly Property QtyReceived() As String
            Get
                Return ResourceManager.GetString("QtyReceived", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Qty Shipped.
        '''</summary>
        Friend Shared ReadOnly Property QtyShipped() As String
            Get
                Return ResourceManager.GetString("QtyShipped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reason.
        '''</summary>
        Friend Shared ReadOnly Property Reason() As String
            Get
                Return ResourceManager.GetString("Reason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipt.
        '''</summary>
        Friend Shared ReadOnly Property Receipt() As String
            Get
                Return ResourceManager.GetString("Receipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipt Date.
        '''</summary>
        Friend Shared ReadOnly Property ReceiptDate() As String
            Get
                Return ResourceManager.GetString("ReceiptDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipt Entry.
        '''</summary>
        Friend Shared ReadOnly Property ReceiptEntry() As String
            Get
                Return ResourceManager.GetString("ReceiptEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ReceiptKey.
        '''</summary>
        Friend Shared ReadOnly Property ReceiptKey() As String
            Get
                Return ResourceManager.GetString("ReceiptKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipt Line#.
        '''</summary>
        Friend Shared ReadOnly Property ReceiptLine() As String
            Get
                Return ResourceManager.GetString("ReceiptLine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Received ASNs KPI.
        '''</summary>
        Friend Shared ReadOnly Property ReceivedASNsKPI() As String
            Get
                Return ResourceManager.GetString("ReceivedASNsKPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Received Goods Report.
        '''</summary>
        Friend Shared ReadOnly Property ReceivedGoodsReport() As String
            Get
                Return ResourceManager.GetString("ReceivedGoodsReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receiving Tally Sheet Report.
        '''</summary>
        Friend Shared ReadOnly Property ReceivingTallySheetReport() As String
            Get
                Return ResourceManager.GetString("ReceivingTallySheetReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to refresh.
        '''</summary>
        Friend Shared ReadOnly Property refresh() As String
            Get
                Return ResourceManager.GetString("refresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Release &amp; Allocate.
        '''</summary>
        Friend Shared ReadOnly Property ReleaseAllocate() As String
            Get
                Return ResourceManager.GetString("ReleaseAllocate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Release to SCE.
        '''</summary>
        Friend Shared ReadOnly Property ReleasetoSCE() As String
            Get
                Return ResourceManager.GetString("ReleasetoSCE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report.
        '''</summary>
        Friend Shared ReadOnly Property Report() As String
            Get
                Return ResourceManager.GetString("Report", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Name.
        '''</summary>
        Friend Shared ReadOnly Property ReportName() As String
            Get
                Return ResourceManager.GetString("ReportName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reports.
        '''</summary>
        Friend Shared ReadOnly Property Reports() As String
            Get
                Return ResourceManager.GetString("Reports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reports &amp; KPIs.
        '''</summary>
        Friend Shared ReadOnly Property ReportsKPIs() As String
            Get
                Return ResourceManager.GetString("ReportsKPIs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Title.
        '''</summary>
        Friend Shared ReadOnly Property ReportTitle() As String
            Get
                Return ResourceManager.GetString("ReportTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Req ShipDate.
        '''</summary>
        Friend Shared ReadOnly Property ReqShipDate() As String
            Get
                Return ResourceManager.GetString("ReqShipDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Requested ShipDate.
        '''</summary>
        Friend Shared ReadOnly Property RequestedShipDate() As String
            Get
                Return ResourceManager.GetString("RequestedShipDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Return to list.
        '''</summary>
        Friend Shared ReadOnly Property Returntolist() As String
            Get
                Return ResourceManager.GetString("Returntolist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property Save() As String
            Get
                Return ResourceManager.GetString("Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SCAC.
        '''</summary>
        Friend Shared ReadOnly Property SCAC() As String
            Get
                Return ResourceManager.GetString("SCAC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Screen Action.
        '''</summary>
        Friend Shared ReadOnly Property ScreenAction() As String
            Get
                Return ResourceManager.GetString("ScreenAction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend Shared ReadOnly Property Search() As String
            Get
                Return ResourceManager.GetString("Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Security.
        '''</summary>
        Friend Shared ReadOnly Property Security() As String
            Get
                Return ResourceManager.GetString("Security", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seller Reference.
        '''</summary>
        Friend Shared ReadOnly Property SellerReference() As String
            Get
                Return ResourceManager.GetString("SellerReference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SERIAL KEY.
        '''</summary>
        Friend Shared ReadOnly Property SERIALKEY() As String
            Get
                Return ResourceManager.GetString("SERIALKEY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipment Order.
        '''</summary>
        Friend Shared ReadOnly Property ShipmentOrder() As String
            Get
                Return ResourceManager.GetString("ShipmentOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipment Order Entry.
        '''</summary>
        Friend Shared ReadOnly Property ShipmentOrderEntry() As String
            Get
                Return ResourceManager.GetString("ShipmentOrderEntry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipment Order Summary Report.
        '''</summary>
        Friend Shared ReadOnly Property ShipmentOrderSummaryReport() As String
            Get
                Return ResourceManager.GetString("ShipmentOrderSummaryReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipped Orders KPI.
        '''</summary>
        Friend Shared ReadOnly Property ShippedOrdersKPI() As String
            Get
                Return ResourceManager.GetString("ShippedOrdersKPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shipped Qty.
        '''</summary>
        Friend Shared ReadOnly Property ShippedQty() As String
            Get
                Return ResourceManager.GetString("ShippedQty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ship To.
        '''</summary>
        Friend Shared ReadOnly Property ShipTo() As String
            Get
                Return ResourceManager.GetString("ShipTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ship To Details.
        '''</summary>
        Friend Shared ReadOnly Property ShipToDetails() As String
            Get
                Return ResourceManager.GetString("ShipToDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show Parameters.
        '''</summary>
        Friend Shared ReadOnly Property ShowParameters() As String
            Get
                Return ResourceManager.GetString("ShowParameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show Report.
        '''</summary>
        Friend Shared ReadOnly Property ShowReport() As String
            Get
                Return ResourceManager.GetString("ShowReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to So.
        '''</summary>
        Friend Shared ReadOnly Property So() As String
            Get
                Return ResourceManager.GetString("So", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State.
        '''</summary>
        Friend Shared ReadOnly Property State() As String
            Get
                Return ResourceManager.GetString("State", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property Status() As String
            Get
                Return ResourceManager.GetString("Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stock Movement Report.
        '''</summary>
        Friend Shared ReadOnly Property StockMovementReport() As String
            Get
                Return ResourceManager.GetString("StockMovementReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stock Report.
        '''</summary>
        Friend Shared ReadOnly Property StockReport() As String
            Get
                Return ResourceManager.GetString("StockReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier.
        '''</summary>
        Friend Shared ReadOnly Property Supplier() As String
            Get
                Return ResourceManager.GetString("Supplier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supplier Details.
        '''</summary>
        Friend Shared ReadOnly Property SupplierDetails() As String
            Get
                Return ResourceManager.GetString("SupplierDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suppliers.
        '''</summary>
        Friend Shared ReadOnly Property Suppliers() As String
            Get
                Return ResourceManager.GetString("Suppliers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tariff Key.
        '''</summary>
        Friend Shared ReadOnly Property TariffKey() As String
            Get
                Return ResourceManager.GetString("TariffKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tarrif Key.
        '''</summary>
        Friend Shared ReadOnly Property TarrifKey() As String
            Get
                Return ResourceManager.GetString("TarrifKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To ASN.
        '''</summary>
        Friend Shared ReadOnly Property ToASN() As String
            Get
                Return ResourceManager.GetString("ToASN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To Customer Order.
        '''</summary>
        Friend Shared ReadOnly Property ToCustomerOrder() As String
            Get
                Return ResourceManager.GetString("ToCustomerOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To Date.
        '''</summary>
        Friend Shared ReadOnly Property ToDate() As String
            Get
                Return ResourceManager.GetString("ToDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To Location.
        '''</summary>
        Friend Shared ReadOnly Property ToLocation() As String
            Get
                Return ResourceManager.GetString("ToLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To LPN.
        '''</summary>
        Friend Shared ReadOnly Property ToLPN() As String
            Get
                Return ResourceManager.GetString("ToLPN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To Order.
        '''</summary>
        Friend Shared ReadOnly Property ToOrder() As String
            Get
                Return ResourceManager.GetString("ToOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To Order Date.
        '''</summary>
        Friend Shared ReadOnly Property ToOrderDate() As String
            Get
                Return ResourceManager.GetString("ToOrderDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To Ship Date.
        '''</summary>
        Friend Shared ReadOnly Property ToShipDate() As String
            Get
                Return ResourceManager.GetString("ToShipDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To Sku.
        '''</summary>
        Friend Shared ReadOnly Property ToSku() As String
            Get
                Return ResourceManager.GetString("ToSku", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To Storer.
        '''</summary>
        Friend Shared ReadOnly Property ToStorer() As String
            Get
                Return ResourceManager.GetString("ToStorer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To Zone.
        '''</summary>
        Friend Shared ReadOnly Property ToZone() As String
            Get
                Return ResourceManager.GetString("ToZone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transportation Mode.
        '''</summary>
        Friend Shared ReadOnly Property TransportationMode() As String
            Get
                Return ResourceManager.GetString("TransportationMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend Shared ReadOnly Property Type() As String
            Get
                Return ResourceManager.GetString("Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UDf1.
        '''</summary>
        Friend Shared ReadOnly Property UDf1() As String
            Get
                Return ResourceManager.GetString("UDf1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UDf2.
        '''</summary>
        Friend Shared ReadOnly Property UDf2() As String
            Get
                Return ResourceManager.GetString("UDf2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UDf3.
        '''</summary>
        Friend Shared ReadOnly Property UDf3() As String
            Get
                Return ResourceManager.GetString("UDf3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UDf4.
        '''</summary>
        Friend Shared ReadOnly Property UDf4() As String
            Get
                Return ResourceManager.GetString("UDf4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UDf5.
        '''</summary>
        Friend Shared ReadOnly Property UDf5() As String
            Get
                Return ResourceManager.GetString("UDf5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UOM.
        '''</summary>
        Friend Shared ReadOnly Property UOM() As String
            Get
                Return ResourceManager.GetString("UOM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE PASSWORD.
        '''</summary>
        Friend Shared ReadOnly Property UPDATEPASSWORD() As String
            Get
                Return ResourceManager.GetString("UPDATEPASSWORD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User.
        '''</summary>
        Friend Shared ReadOnly Property User() As String
            Get
                Return ResourceManager.GetString("User", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Control.
        '''</summary>
        Friend Shared ReadOnly Property UserControl() As String
            Get
                Return ResourceManager.GetString("UserControl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Control Details.
        '''</summary>
        Friend Shared ReadOnly Property UserControlDetails() As String
            Get
                Return ResourceManager.GetString("UserControlDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Details.
        '''</summary>
        Friend Shared ReadOnly Property UserDetails() As String
            Get
                Return ResourceManager.GetString("UserDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Facility.
        '''</summary>
        Friend Shared ReadOnly Property UserFacility() As String
            Get
                Return ResourceManager.GetString("UserFacility", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User ID.
        '''</summary>
        Friend Shared ReadOnly Property UserID() As String
            Get
                Return ResourceManager.GetString("UserID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Profile.
        '''</summary>
        Friend Shared ReadOnly Property UserProfile() As String
            Get
                Return ResourceManager.GetString("UserProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Users.
        '''</summary>
        Friend Shared ReadOnly Property Users() As String
            Get
                Return ResourceManager.GetString("Users", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View.
        '''</summary>
        Friend Shared ReadOnly Property View() As String
            Get
                Return ResourceManager.GetString("View", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View Reports.
        '''</summary>
        Friend Shared ReadOnly Property ViewReports() As String
            Get
                Return ResourceManager.GetString("ViewReports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse.
        '''</summary>
        Friend Shared ReadOnly Property Warehouse() As String
            Get
                Return ResourceManager.GetString("Warehouse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse Ref.
        '''</summary>
        Friend Shared ReadOnly Property WarehouseRef() As String
            Get
                Return ResourceManager.GetString("WarehouseRef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse Reference.
        '''</summary>
        Friend Shared ReadOnly Property WarehouseReference() As String
            Get
                Return ResourceManager.GetString("WarehouseReference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warehouse Summary Report.
        '''</summary>
        Friend Shared ReadOnly Property WarehouseSummaryReport() As String
            Get
                Return ResourceManager.GetString("WarehouseSummaryReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome.
        '''</summary>
        Friend Shared ReadOnly Property Welcome() As String
            Get
                Return ResourceManager.GetString("Welcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wmid.
        '''</summary>
        Friend Shared ReadOnly Property wmid() As String
            Get
                Return ResourceManager.GetString("wmid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to wmsid.
        '''</summary>
        Friend Shared ReadOnly Property wmsid() As String
            Get
                Return ResourceManager.GetString("wmsid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WMS OrderKey.
        '''</summary>
        Friend Shared ReadOnly Property WMSOrderKey() As String
            Get
                Return ResourceManager.GetString("WMSOrderKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend Shared ReadOnly Property Yes() As String
            Get
                Return ResourceManager.GetString("Yes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zip.
        '''</summary>
        Friend Shared ReadOnly Property Zip() As String
            Get
                Return ResourceManager.GetString("Zip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zip Code.
        '''</summary>
        Friend Shared ReadOnly Property ZipCode() As String
            Get
                Return ResourceManager.GetString("ZipCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date.
        '''</summary>
        Friend Shared ReadOnly Property _Date() As String
            Get
                Return ResourceManager.GetString("Date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend Shared ReadOnly Property _New() As String
            Get
                Return ResourceManager.GetString("New", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Read Only.
        '''</summary>
        Friend Shared ReadOnly Property _ReadOnly() As String
            Get
                Return ResourceManager.GetString("ReadOnly", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
